import type { Metadata } from "next";
import { Inter } from "next/font/google";
import NavBar from "@/app/ui/navigation/NavBar";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type LayoutProps = Readonly<{
  children: React.ReactNode;
}>;

export default function RootLayout({ children }: LayoutProps) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NavBar />
        <main className=" h-full flex items-center justify-center flex-col gap-8">
          {children}
        </main>
      </body>
    </html>
  );
}
